# Generated by Django 2.0.4 on 2018-06-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('book_type', models.CharField(choices=[('BOOK', 'Libro comun'), ('COMIC', 'Comic'), ('ESPECIAL_BOOK', 'Lectura especializada'), ('KIDS_BOOK', 'Lectura infantil')], default='BOOK', max_length=20)),
                ('genre', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=20)),
                ('original', models.CharField(choices=[('YES', 'Original'), ('NO', 'No original')], default='Original', max_length=20)),
                ('transaction', models.CharField(choices=[('EXCHANGE', 'Intercambio'), ('SALE', 'Venta'), ('BOTH', 'Ambos')], default='Intercambio', max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='book/picture_books')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUT', models.CharField(max_length=15)),
                ('commune', models.CharField(max_length=20)),
                ('phone', models.PositiveIntegerField()),
                ('fav_genre', models.CharField(choices=[('FANTASY', 'Fantasía'), ('FICTION', 'Ficción'), ('HORROR', 'Terror'), ('ROMANTIC', 'Romantico')], default='Ninguno', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User'),
        ),
    ]
