# Generated by Django 2.0.1 on 2018-06-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180624_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='fav_genre',
        ),
    ]
