# Generated by Django 2.0.1 on 2018-06-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180624_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('book_type', models.CharField(choices=[('BOOK', 'Libro comun'), ('COMIC', 'Comic'), ('ESPECIAL_BOOK', 'Lectura especializada'), ('KIDS_BOOK', 'Lectura infantil')], default='BOOK', max_length=20)),
                ('genre', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=20)),
                ('original', models.CharField(choices=[('YES', 'Original'), ('NO', 'No original')], default='Original', max_length=20)),
                ('transaction', models.CharField(choices=[('EXCHANGE', 'Intercambio'), ('SALE', 'Venta'), ('BOTH', 'Ambos')], default='Intercambio', max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='book/picture_books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.UserBook')),
            ],
        ),
    ]
