# Generated by Django 2.0.1 on 2018-06-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20180626_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
